--requerimiento 1

SELECT AVG(SALARY) AS "SALARIO PROMEDIO", MIN(SALARY) AS "SALARIO MINIMO", MAX (SALARY) AS "SALARIO MAXIMO" 
FROM employees 
WHERE commission_pct IS NOT NULL;

--requerimiento 2

SELECT UPPER(first_name| |'  '| | last_name) AS "NOMBRE COMPLETO", NVL(commission_pct,0) AS " PORCENTAJE DE COMISION", department_id AS "NRO DEPARTAMENTO"
FROM EMPLOYEES 
WHERE department_id BETWEEN 50 AND 90;

--requerimiento 3

SELECT TO_CHAR(AVG(SALARY),'$99,999') AS "SALARIO PROMEDIO",  TO_CHAR(MIN(SALARY),'$99,999') AS "SALARIO MINIMO",  TO_CHAR(MAX(SALARY),'$99,999') AS "SALARIO MAXIMO" 
FROM EMPLOYEES
WHERE department_id = 110 AND commission_pct is null; 

-- requerimiento 4

SELECT (first_name| |'  '| | last_name) AS "NOMBRE COMPLETO", employee_id AS "CODIGO DE EMPLEADO", TO_CHAR (HIRE_DATE,'dd-mm-yyyy') AS "FECHA DE CONTRATO", CONCAT (LOWER(EMAIL), '@hr.cl') AS "CORREO ELECTRONICO", SALARY AS "SALARIO"  
FROM EMPLOYEES
WHERE HIRE_DATE <= CAST('22/05/2005' AS DATE) AND SALARY <10000 ;
--SELECT * FROM EMPLOYEES;

