CREATE TABLE TIPO_PROPIEDAD (
    ID_TIPO_PROPIEDAD NUMBER(2) 
    , DESC_TIPO_PROPIEDAD VARCHAR2(30)
    
    , CONSTRAINT INDEX_3 PRIMARY KEY (ID_TIPO_PROPIEDAD)
);

CREATE TABLE PROPIETARIO (
    NUMRUT_PROP NUMBER(10) NOT NULL 
    , DVRUT_PROP NUMBER(1)
    , APPATERNO_PROP VARCHAR2(15)
    , APMATERNO_PROP VARCHAR2(15)
    , NOMBRE_PROP VARCHAR(15)
    , DIRECCION_PROP VARCHAR2(60)
    , FONOFIJO_PROP VARCHAR2(15)
    , CELULAR_PROP VARCHAR2(15)
    
    , CONSTRAINT PK_PROPIETARIO PRIMARY KEY (NUMRUT_PROP)
);

CREATE TABLE EMPLEADO (
    NUMRUT_EMP NUMBER(10) NOT NULL 
    , DVRUT_EMP NUMBER(1)
    , APPATERNO_EMP VARCHAR2(15)
    , APMATERNO_EMP VARCHAR2(15)
    , NOMBRE_EMP VARCHAR(15)
    , DIRECCION_EMP VARCHAR2(60)
    , FONOFIJO_EMP VARCHAR2(15)
    , CELULAR_EMP VARCHAR2(15)
    , FECNAC_EMP DATE
    , FECING_EMP DATE DEFAULT SYSDATE
    , SUELDO_EMP NUMBER(7)
    
    , ID_CATEGORIA_EMP NUMBER(1)
    , ID_SUCURSAL NUMBER
    
    , CONSTRAINT PK_NUMRUT_EMP PRIMARY KEY (NUMRUT_EMP) 
    
    , CONSTRAINT FK_ID_CATEGORIA_EMP FOREIGN KEY(ID_CATEGORIA_EMP) REFERENCES CATEGORIA_EMPLEADO(ID_CATEGORIA_EMP)
    , CONSTRAINT FK_ID_SUCURSAL FOREIGN KEY(ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL)
);

CREATE TABLE IMPUESTO(
    NUMRUT_EMP NUMBER(10) NOT NULL 
    , DVRUT_EMP NUMBER(1) NOT NULL
    , SUELDO_EMP_ENERO_MARZO NUMBER(10)
    , IMPTO_EMP_ENERO_MARZO NUMBER(8)
    
    , CONSTRAINT FK_NUMRUT_EMP FOREIGN KEY(NUMRUT_EMP) REFERENCES EMPLEADO(NUMRUT_EMP) 
);

CREATE TABLE PROPIEDAD(
    NRO_PROPIEDAD NUMBER(10) NOT NULL 
    , DIRECCION_PROPIEDAD VARCHAR2(60)
    , SUPERFICIE NUMBER(5,2)
    , NRO_DORMITORIOS NUMBER(1) DEFAULT 0 NOT NULL
    , NRO_BANOS NUMBER(1) DEFAULT 0 NOT NULL
    , VALOR_ARRIENDO NUMBER(7) CONSTRAINT CK_VALOR_ARRIENDO_EMP_COPIA CHECK (VALOR_ARRIENDO < 250000000)
    , VALOR_GASTO_COMUN NUMBER(6) CONSTRAINT CK_VALOR_GASTO_COMUN_EMP_COPIA CHECK (VALOR_GASTO_COMUN > 250000)
    
    , ID_TIPO_PROPIEDAD NUMBER(2)
    , ID_COMUNA NUMBER(3)
    , NUMRUT_PROP NUMBER(10)
    , NUMRUT_EMP NUMBER(10)

    , CONSTRAINT PK_NRO_PROPIEDAD PRIMARY KEY (NRO_PROPIEDAD)

    , CONSTRAINT FK_ID_TIPO_PROPIEDAD FOREIGN KEY(ID_TIPO_PROPIEDAD) REFERENCES TIPO_PROPIEDAD(ID_TIPO_PROPIEDAD) 
    , CONSTRAINT FK_ID_COMUNA FOREIGN KEY(ID_COMUNA) REFERENCES COMUNA(ID_COMUNA) 
    , CONSTRAINT FK_NUMRUT_PROP FOREIGN KEY(NUMRUT_PROP) REFERENCES PROPIETARIO(NUMRUT_PROP) 
    , CONSTRAINT FK_NUMRUT_EMPL FOREIGN KEY(NUMRUT_EMP) REFERENCES EMPLEADO(NUMRUT_EMP) 
);

CREATE TABLE ARRIENDO_PROPIEDAD(
    NRO_PROPIEDAD NUMBER NOT NULL 
    , NUMRUT_CLI NUMBER(10) NOT NULL
    , FECINI_ARRIENDO DATE
    , FECTER_ARRIENDO DATE
       
    , CONSTRAINT FK_NRO_PROPIEDAD FOREIGN KEY(NRO_PROPIEDAD) REFERENCES PROPIEDAD(NRO_PROPIEDAD) 
    , CONSTRAINT FK_NUMRUT_CLI FOREIGN KEY(NUMRUT_CLI) REFERENCES CLIENTE(NUMRUT_CLI) 
);

CREATE SEQUENCE TIPO_PROPIEDAD_SEQ 
    INCREMENT BY 3
    START WITH 10
    MAXVALUE 100
    NOCACHE
    NOCYCLE;    

INSERT INTO EMPLEADO (NUMRUT_EMP, DVRUT_EMP, APPATERNO_EMP, APMATERNO_EMP, NOMBRE_EMP, DIRECCION_EMP, FONOFIJO_EMP, CELULAR_EMP, FECNAC_EMP, FECING_EMP, SUELDO_EMP, ID_CATEGORIA_EMP, ID_SUCURSAL) 
VALUES (965443, 9, 'perez', 'cotapo', 'juanito', 'avenida siempre viva 742', 453219, 896321, to_date('2001/01/20','YYYY-MM-DD'), to_date('2009/05/20','YYYY-MM-DD'), 25600, 1, 1);
INSERT INTO EMPLEADO (NUMRUT_EMP, DVRUT_EMP, APPATERNO_EMP, APMATERNO_EMP, NOMBRE_EMP, DIRECCION_EMP, FONOFIJO_EMP, CELULAR_EMP, FECNAC_EMP, FECING_EMP, SUELDO_EMP, ID_CATEGORIA_EMP, ID_SUCURSAL) 
VALUES (858565, 6, 'jimenez', 'rivera', 'ricardo', 'P. Sherman, calle Wallaby, 42,', 563259, 753159, to_date('1752/01/25','YYYY-MM-DD'), to_date('1850/01/26','YYYY-MM-DD'), 543215, 2, 2);

INSERT INTO IMPUESTO (NUMRUT_EMP, DVRUT_EMP, SUELDO_EMP_ENERO_MARZO, IMPTO_EMP_ENERO_MARZO) VALUES (858565, 6 , 854625, 10000);
INSERT INTO IMPUESTO (NUMRUT_EMP, DVRUT_EMP, SUELDO_EMP_ENERO_MARZO, IMPTO_EMP_ENERO_MARZO) VALUES (965443, 9, 851233, 63333);

INSERT INTO PROPIETARIO (NUMRUT_PROP, DVRUT_PROP, APPATERNO_PROP, APMATERNO_PROP, NOMBRE_PROP, DIRECCION_PROP, FONOFIJO_PROP, CELULAR_PROP) 
VALUES (562312, 4, 'perez', 'castro', 'carlos', 'calle 123', 562389, 771133);
INSERT INTO PROPIETARIO (NUMRUT_PROP, DVRUT_PROP, APPATERNO_PROP, APMATERNO_PROP, NOMBRE_PROP, DIRECCION_PROP, FONOFIJO_PROP, CELULAR_PROP) 
VALUES (415263, 4, 'moreno', 'rojas', 'alberto', 'valle 123', 856325, 963211);

INSERT INTO TIPO_PROPIEDAD (ID_TIPO_PROPIEDAD, DESC_TIPO_PROPIEDAD) VALUES (TIPO_PROPIEDAD_SEQ.NEXTVAL, 'CASA');
INSERT INTO TIPO_PROPIEDAD (ID_TIPO_PROPIEDAD, DESC_TIPO_PROPIEDAD) VALUES (TIPO_PROPIEDAD_SEQ.NEXTVAL,'DEPARTAMENTO');
INSERT INTO TIPO_PROPIEDAD (ID_TIPO_PROPIEDAD, DESC_TIPO_PROPIEDAD) VALUES (TIPO_PROPIEDAD_SEQ.NEXTVAL, 'LOCAL');
INSERT INTO TIPO_PROPIEDAD (ID_TIPO_PROPIEDAD, DESC_TIPO_PROPIEDAD) VALUES (TIPO_PROPIEDAD_SEQ.NEXTVAL,'PARCELA SIN CASA');
INSERT INTO TIPO_PROPIEDAD (ID_TIPO_PROPIEDAD, DESC_TIPO_PROPIEDAD) VALUES (TIPO_PROPIEDAD_SEQ.NEXTVAL, 'PARCELA CON CASA');

INSERT INTO PROPIEDAD (NRO_PROPIEDAD, DIRECCION_PROPIEDAD, SUPERFICIE, NRO_DORMITORIOS, NRO_BANOS, VALOR_ARRIENDO, VALOR_GASTO_COMUN, ID_TIPO_PROPIEDAD, ID_COMUNA, NUMRUT_PROP, NUMRUT_EMP) 
VALUES (1,' avenida siempre viva 12', 50, default, default, 50000, 400000, 16, 1, 562312, 858565);
INSERT INTO PROPIEDAD (NRO_PROPIEDAD, DIRECCION_PROPIEDAD, SUPERFICIE, NRO_DORMITORIOS, NRO_BANOS, VALOR_ARRIENDO, VALOR_GASTO_COMUN, ID_TIPO_PROPIEDAD, ID_COMUNA, NUMRUT_PROP, NUMRUT_EMP) 
VALUES (2,' avenida viva 1', 55, default, default, 40000, 300000, 19, 2, 562312, 858565);

INSERT INTO ARRIENDO_PROPIEDAD (NRO_PROPIEDAD, NUMRUT_CLI, FECINI_ARRIENDO, FECTER_ARRIENDO) VALUES (1, 12345678, to_date('2011/04/22','YYYY-MM-DD'), to_date('2011/04/22','YYYY-MM-DD'));
INSERT INTO ARRIENDO_PROPIEDAD (NRO_PROPIEDAD, NUMRUT_CLI, FECINI_ARRIENDO, FECTER_ARRIENDO) VALUES (2, 87654321, to_date('2011/04/22','YYYY-MM-DD'), to_date('2011/04/22','YYYY-MM-DD'));



